version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - appnet
    restart: unless-stopped

  app:
    build:
      context: ./app
    volumes:
      - ./app:/var/www/html
    networks:
      - appnet
    expose:
      - "9000"
    depends_on:
      - mysql_user

  mysql_user:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_user
    volumes:
      - mysql_user:/var/lib/mysql
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:

volumes:
  mysql_user:
